version: '3.8'

services:
  nethermind:
    image: nethermind/nethermind
    container_name: nethermind
    volumes:
      - ./nethermind.config.json:/home/nethermind/.nethermind/config.json
      - ./jwtsecret:/data/jwtsecret
      - nethermind_data:/data
    ports:
      - "8545:8545"   # JSON-RPC port
      - "8546:8546"   # WebSocket port
      - "30303:30303" # P2P port
      - "9090:9090"   # Prometheus metrics
      - "8551:8551"   # Engine JSON-RPC port
    command: -c /home/nethermind/.nethermind/config.json

  teku:
    image: edwards-custom-teku
    container_name: teku
    volumes:
      - ./jwtsecret:/data/jwtsecret
      - teku_data:/opt/teku/data
    ports:
      - "8008:8008"   # Prometheus metrics
      - "5051:5051"   # REST API port

volumes:
  nethermind_data:
  teku_data:
